### ISSUE TITLE
Orio support

### ISSUE THREAD

**Issue by PragmaticEd** [XspeedPL/PhysicalButtonMod#2]
Have there been any test on Orio for this?

I know it doesn't work right now, but any possibility that it could get Android Orio support?

**Comment by XspeedPL** [comment]
I had multiple reports from people with Oreo confirming that it works on the XDA thread.
Don't know about Orio though, is it some kind of bootleg? :P

**Comment by PragmaticEd** [comment]
@XspeedPL  "orio" xD xD I mean Oreo, ofc.. :D   I will go and try to find those ppl and ask there os versions :) Thanks.

**Comment by XspeedPL** [comment]
You can post your information here. Turn on the debug log, restart your device, try using some of the features, then dump the Xposed log here. If there's anything wrong I might get some clues what needs to be done.
