### ISSUE TITLE
Keypress Menu is emulated? 

### ISSUE THREAD

**Issue by ildar** [XspeedPL/PhysicalButtonMod#4]
Real keypress is very different from "Open menu" action. 
I can see both in e.g. Keyboard/Button Mapper https://f-droid.org/packages/io.github.sds100.keymapper
The problem is that Physical Button Mapper acts like the second yet declaring the first. Could you please clarify?

**Comment by XspeedPL** [comment]
"Open menu" action?

**Comment by ildar** [comment]
Sorry, i don't know how to name it right.
Keyboard/Button Mapper has it in "Other" actions tab. The result is
identical.
Yet emulating physical "Menu" button press has different effect in apps.

**Comment by XspeedPL** [comment]
I took a look at the source of KeyMapper (file ActionPerformerDelegate.kt), and what it does is either inject a KEYCODE_MENU key event using a shell command if root permission is granted or find the menu overflow element on the current screen and simulate a click on it using an accessibility service.
All in all, pretty standard procedure.

On the other hand, PBMC always injects the key events on system level, it's the closest to "real key press" you can get, leveraging the powerful Xposed Framework. The key presses injected by PBMC are processed faster, they are indistinguishable from real key presses by both apps and the Android system itself.

**Comment by ildar** [comment]
Piotr,
I intensively tested KeyMapper these weeks. I found it working good except that it uses (root) shell to inject key events. Which is very slow for a modern user.
Unfortunately PBMC doesn't work for me in a similar way. I observe just "menu overflow" behavior pattern. Many apps that react on Menu Key press stay silent when PBMC injects. What could be the problem?
My setup is Android 7.1 stock.
thank you for the app.

**Comment by XspeedPL** [comment]
Could you list apps that have problems reacting to the menu key?
In my testing all apps that react to the hardware menu key (using an external keyboard) react to PBMC in the same way.

**Comment by ildar** [comment]
KISS Launcher - https://f-droid.org/packages/fr.neamar.kiss @ main screen

https://play.google.com/store/apps/details?id=citybus.guidejet.com @
Tracking tab

If you need more please ask.
Thanks.

**Comment by XspeedPL** [comment]
The first application displays the context menu with settings when menu key is injected by PBMC.
Tested on Android 8 and 9.

The second app is country blocked for me.

Are you sure your chain is being executed correctly? You can add a notification action with a toast to get visual feedback.
![Screenshot_20201103-212414](https://user-images.githubusercontent.com/1101440/98036858-01ea1380-1e1b-11eb-819a-f9aab41525dd.png)

**Comment by XspeedPL** [comment]
Closed from lack of activity
